# Generated by Django 4.2.2 on 2024-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenderevent',
            name='is_on_date',
            field=models.BooleanField(default=False),
        ),
    ]
