# Generated by Django 4.2.2 on 2024-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_child_image_alter_child_local_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='attendance_rate',
            field=models.IntegerField(default=1),
        ),
    ]
