# Generated by Django 5.0.4 on 2024-05-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_event_remove_eventactivity_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderofevent',
            name='events',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='orderofevent',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='order_of_events',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='church',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='offering_amount',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='tithe_amount',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='OrderOfEvent',
        ),
    ]
