# Generated by Django 4.2.2 on 2024-04-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_child_attendance_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='child_images'),
        ),
    ]
