# Generated by Django 4.2.2 on 2024-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_child_gender_parent_home_county_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='talent',
            field=models.CharField(blank=True, choices=[('Praise & Worship', 'Praise & Worship'), ('Giving', 'Giving'), ('Singing', 'Singing')], max_length=20, null=True),
        ),
    ]
