# Generated by Django 5.0.4 on 2024-05-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_eventactivity_offering_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalenderEvent',
            new_name='ChildrenMinistryEvent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='associate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='church',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='offering_amount',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='order_of_events',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='tithe_amount',
        ),
        migrations.RemoveField(
            model_name='orderofevent',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='orderofevent',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='orderofevent',
            name='events',
        ),
    ]
