# Generated by Django 5.0.4 on 2024-05-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_calenderevent_childrenministryevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventActivity',
        ),
        migrations.DeleteModel(
            name='OrderOfEvent',
        ),
    ]
