# Generated by Django 4.2.2 on 2024-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_child_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
