# Generated by Django 5.0.4 on 2024-05-08 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_delete_event_delete_eventactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(default=None, max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
                ('event', models.CharField(choices=[('1st Reading', '1st Reading'), ('Praise and worship', 'Praise and worship'), ('Testimonies', 'Testimonies'), ('Visitors', 'Visitors'), ('Sermon', 'Sermon'), ('Opening prayer', 'Opening prayer'), ('Closing prayer', 'Closing prayer'), ('Hymns', 'Hymns'), ('2nd Reading', '2nd Reading'), ('Intercessory', 'Intercessory')], max_length=100)),
                ('associate', models.CharField(default=None, max_length=100)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('South B', 'South B'), ('Kiambiu', 'Kiambiu'), ('Kitengela', 'Kitengela'), ('Waudo', 'Waudo'), ('Eastleigh', 'Eastleigh'), ('Umoja', 'Umoja'), ('Muthaiga', 'Muthaiga'), ('Runda', 'Runda'), ('Kariokor', 'Kariokor'), ('KMM', 'KMM')], max_length=20)),
                ('offering_amount', models.IntegerField(default=0)),
                ('tithe_amount', models.IntegerField(default=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.event')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.childrenministryevent')),
                ('events', models.ManyToManyField(related_name='events', through='register.EventActivity', to='register.event')),
            ],
        ),
        migrations.AddField(
            model_name='eventactivity',
            name='order_of_events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.orderofevent'),
        ),
    ]
