# Generated by Django 4.2.2 on 2024-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_parent_father_name_alter_parent_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
