# Generated by Django 5.0.4 on 2024-05-08 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_orderofevent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventactivity',
            name='church',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='offering_amount',
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='tithe_amount',
        ),
        migrations.AddField(
            model_name='orderofevent',
            name='offering_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderofevent',
            name='tithe_amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='orderofevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
