# Generated by Django 5.0.4 on 2024-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_remove_eventactivity_church_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderofevent',
            name='user',
        ),
        migrations.AddField(
            model_name='orderofevent',
            name='local_church',
            field=models.CharField(default='Kiambiu', max_length=20),
        ),
    ]
