# Generated by Django 4.2.2 on 2024-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_sundayactivity_alter_attendance_lesson_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayactivity',
            name='on_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
