# Generated by Django 5.0.4 on 2024-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_remove_orderofevent_user_orderofevent_local_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofevent',
            name='local_church',
            field=models.CharField(max_length=20),
        ),
    ]
