# Generated by Django 4.2.2 on 2024-04-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_rename_lesson_attendance_sunday_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('on_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('church', models.CharField(choices=[('South B', 'South B'), ('Kiambiu', 'Kiambiu'), ('Kitengela', 'Kitengela'), ('Waudo', 'Waudo'), ('Eastleigh', 'Eastleigh'), ('Umoja', 'Umoja'), ('Muthaiga', 'Muthaiga'), ('Runda', 'Runda'), ('Kariokor', 'Kariokor'), ('KMM', 'KMM')], max_length=20)),
                ('event', models.TextField(max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.calenderevent')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sunday_activity',
        ),
        migrations.AlterField(
            model_name='child',
            name='local_church',
            field=models.CharField(choices=[('South B', 'South B'), ('Kiambiu', 'Kiambiu'), ('Kitengela', 'Kitengela'), ('Waudo', 'Waudo'), ('Eastleigh', 'Eastleigh'), ('Umoja', 'Umoja'), ('Muthaiga', 'Muthaiga'), ('Runda', 'Runda'), ('Kariokor', 'Kariokor'), ('KMM', 'KMM')], max_length=100),
        ),
        migrations.DeleteModel(
            name='SundayActivity',
        ),
        migrations.AddField(
            model_name='calenderevent',
            name='children_attendance',
            field=models.ManyToManyField(related_name='lessons_attended', through='register.Attendance', to='register.child'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register.calenderevent'),
            preserve_default=False,
        ),
    ]
