# Generated by Django 5.0.4 on 2024-05-09 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_event_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='phone_number',
            new_name='father_phone_number',
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.childrenministryevent'),
        ),
    ]
