# Generated by Django 4.2.2 on 2024-04-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_eventactivity_church'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='child_attendance',
            new_name='child',
        ),
    ]
