# Generated by Django 5.0.4 on 2024-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_rename_phone_number_parent_father_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenministryevent',
            name='details',
            field=models.TextField(max_length=50),
        ),
    ]
