# Generated by Django 5.0.4 on 2024-05-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_alter_childrenministryevent_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderofevent',
            name='offering_amount',
        ),
        migrations.RemoveField(
            model_name='orderofevent',
            name='tithe_amount',
        ),
    ]
